channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.0.2
- pip:
  - mlflow==2.14.3
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - xgboost==2.1.0
name: mlflow-env
